version: '3.6'

services:
  user_api:
    build:
      context: "."
      dockerfile: "./api/user/app.dockerfile"
    depends_on:
      - "user_api_db"
    environment:
      DATABASE_URL: "postgres://grepc-test:123456@user_api_db/grepc-test?sslmode=disable"
    restart: "unless-stopped"
  user_api_db:
    build:
      context: "./api/user"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grepc-test"
      POSTGRES_USER: "grepc-test"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"