[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "master"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  branch = "master"