// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/user/pb/user.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	api/user/pb/user.proto

It has these top-level messages:
	User
	GetUserRequest
	GetUserResponse
	PostUserRequest
	PostUserResponse
	UpdateUserRequest
	UpdateUserResponse
	DeleteUserRequest
	DeleteUserResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// @inject_tag: sql:"type:timestamptz"
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type PostUserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *PostUserRequest) Reset()                    { *m = PostUserRequest{} }
func (m *PostUserRequest) String() string            { return proto.CompactTextString(m) }
func (*PostUserRequest) ProtoMessage()               {}
func (*PostUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PostUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PostUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PostUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *PostUserResponse) Reset()                    { *m = PostUserResponse{} }
func (m *PostUserResponse) String() string            { return proto.CompactTextString(m) }
func (*PostUserResponse) ProtoMessage()               {}
func (*PostUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PostUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserResponse struct {
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "pb.GetUserResponse")
	proto.RegisterType((*PostUserRequest)(nil), "pb.PostUserRequest")
	proto.RegisterType((*PostUserResponse)(nil), "pb.PostUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "pb.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "pb.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "pb.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "pb.DeleteUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*PostUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*PostUserResponse, error) {
	out := new(PostUserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/PostUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	PostUser(context.Context, *PostUserRequest) (*PostUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PostUser(ctx, req.(*PostUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "PostUser",
			Handler:    _UserService_PostUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/pb/user.proto",
}

func init() { proto.RegisterFile("api/user/pb/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0xb0, 0x85, 0xed, 0x2c, 0x6a, 0xd9, 0xe9, 0x52, 0x82, 0x55, 0x89, 0x55, 0xb8,
	0x54, 0x3d, 0x24, 0x10, 0x4e, 0x70, 0xab, 0x00, 0x71, 0x02, 0xa1, 0xa5, 0xe5, 0x8a, 0x9c, 0x66,
	0xa8, 0x2c, 0x6d, 0x62, 0x13, 0x3b, 0xbd, 0x20, 0x2e, 0xbc, 0x02, 0xef, 0xc3, 0x4b, 0x70, 0xe3,
	0xcc, 0x83, 0xa0, 0xd8, 0x49, 0x37, 0x7f, 0x84, 0x58, 0xa9, 0xa7, 0xc8, 0xe3, 0x6f, 0xbe, 0xf1,
	0xf7, 0xcb, 0xc0, 0x21, 0x57, 0x22, 0xae, 0x34, 0x95, 0xb1, 0x4a, 0xed, 0x37, 0x52, 0xa5, 0x34,
	0x12, 0x7d, 0x95, 0xb2, 0xa3, 0x4b, 0x29, 0x2f, 0xd7, 0x14, 0xd7, 0x12, 0x5e, 0x14, 0xd2, 0x70,
	0x23, 0x64, 0xa1, 0x9d, 0x82, 0x3d, 0x6a, 0x6e, 0xed, 0x29, 0xad, 0x3e, 0xc7, 0x46, 0xe4, 0xa4,
	0x0d, 0xcf, 0x95, 0x13, 0x84, 0x3f, 0x3d, 0x98, 0x9c, 0x6b, 0x2a, 0x71, 0x0f, 0x7c, 0x91, 0x05,
	0xde, 0xd2, 0x3b, 0xde, 0x5d, 0xf9, 0x22, 0x43, 0x06, 0xd3, 0x7a, 0x52, 0xc1, 0x73, 0x0a, 0x7c,
	0x5b, 0xbd, 0x3e, 0xe3, 0x02, 0x76, 0x28, 0xe7, 0x62, 0x1d, 0xdc, 0xb2, 0x17, 0xee, 0x80, 0xcf,
	0x01, 0x2e, 0x4a, 0xe2, 0x86, 0xb2, 0x4f, 0xdc, 0x04, 0x93, 0xa5, 0x77, 0x3c, 0x4b, 0x58, 0xe4,
	0x1e, 0x10, 0xb5, 0x0f, 0x88, 0xce, 0xda, 0x07, 0xac, 0x76, 0x1b, 0xf5, 0xa9, 0xa9, 0x5b, 0x2b,
	0x95, 0xb5, 0xad, 0x3b, 0xff, 0x6f, 0x6d, 0xd4, 0xa7, 0x26, 0x5c, 0xc2, 0xde, 0x1b, 0x32, 0x75,
	0x84, 0x15, 0x7d, 0xa9, 0x48, 0x9b, 0x61, 0x92, 0x30, 0x86, 0xfd, 0x6b, 0x85, 0x56, 0xb2, 0xd0,
	0x84, 0x47, 0x30, 0xa9, 0xc3, 0x58, 0xd1, 0x2c, 0x99, 0x46, 0x2a, 0x8d, 0xec, 0xbd, 0xad, 0x86,
	0x2f, 0x61, 0xff, 0xbd, 0xd4, 0x3d, 0xcf, 0x2e, 0x0d, 0xef, 0x5f, 0x34, 0xfc, 0x0e, 0x8d, 0xf0,
	0x09, 0xdc, 0xdb, 0x98, 0x6c, 0x35, 0xf6, 0x35, 0xcc, 0xcf, 0x6d, 0xac, 0x9b, 0x0d, 0x4e, 0x00,
	0xbb, 0x36, 0x5b, 0x8d, 0x7e, 0x0c, 0xf3, 0x57, 0xb4, 0xa6, 0xfe, 0xe8, 0x21, 0xc7, 0x05, 0x60,
	0x57, 0xe4, 0x8c, 0x93, 0xdf, 0x3e, 0xcc, 0xea, 0xc2, 0x07, 0x2a, 0xaf, 0xc4, 0x05, 0xe1, 0x5b,
	0xb8, 0xd3, 0xd0, 0x46, 0xac, 0xa7, 0xf4, 0x7f, 0x0e, 0x3b, 0xe8, 0xd5, 0x9c, 0x47, 0xf8, 0xf0,
	0xfb, 0xaf, 0x3f, 0x3f, 0xfc, 0x03, 0x9c, 0xdb, 0x2d, 0xbe, 0x7a, 0xea, 0x76, 0xfd, 0xab, 0xc8,
	0xbe, 0xe1, 0x3b, 0x98, 0xb6, 0x18, 0xd1, 0xf6, 0x0e, 0xfe, 0x0c, 0x5b, 0xf4, 0x8b, 0x8d, 0xe3,
	0x03, 0xeb, 0x38, 0x0f, 0xef, 0x76, 0x1d, 0x5f, 0x78, 0x27, 0x78, 0x06, 0xb0, 0xa1, 0x83, 0xf7,
	0x2d, 0x87, 0x21, 0x74, 0x76, 0x38, 0x2c, 0xf7, 0x5d, 0xd9, 0xc8, 0xf5, 0x23, 0xc0, 0x06, 0x8d,
	0x73, 0x1d, 0xf1, 0x74, 0xae, 0x63, 0x82, 0x6d, 0xfa, 0x93, 0x71, 0xfa, 0xf4, 0xb6, 0xdd, 0xfd,
	0x67, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xf6, 0x1b, 0xf9, 0x01, 0x04, 0x00, 0x00,
}
